# Generated by Django 4.2.6 on 2023-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
